server:
  port: 9998
  tomcat:
    max-swallow-size: 100MB
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      #      最大请求内存
      max-request-size: 10MB
      #      最大的文件内存
      max-file-size: 10MB
      resolve-lazily: true
      #      file-size-threshold: 100MB
      #设置临时文件夹，防止tomcat启动后文件上传，会出现自动删除临时文件夹的问题
      location: /temp/spring-project-base/storage/directory
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aliex-base?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
    username: root
    password: 12345678
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000

  jpa:
    hibernate:
      ddl-auto: update

#限流熔断机制
# sentinel看板的地址
  cloud:
    sentinel:
      transport:
        dashboard: localhost:9000
# 开启对sentinel看板的饥饿式加载。sentinel默认是懒加载机制，只有访问过一次的资源才会被监控，通过关闭懒加载，在项目启动时就连接sentinel控制台
      eager: true